export const dummyBabyProducts = [
  {
    _id: "baby_1",
    name: "Soft Organic Cotton Onesie",
    description: "Breathable, 100% organic cotton onesie perfect for everyday wear. Gentle on baby's sensitive skin with easy snap closures.",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&q=80",
    category: "clothes",
    isFeatured: true,
    isOnSale: false,
  },
  {
    _id: "baby_2",
    name: "Ergonomic Baby Carrier",
    description: "Comfortable and supportive baby carrier allowing multiple carrying positions. Designed for optimal weight distribution.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1491013516836-7dbf43681043?w=800&q=80",
    category: "gear",
    isFeatured: true,
    isOnSale: true,
    discountPercent: 15,
  },
  {
    _id: "baby_3",
    name: "Soothing Nursery Night Light",
    description: "Dimmable LED night light with soft color options and built-in lullabies to help soothe your baby to sleep.",
    price: 34.50,
    image: "https://images.unsplash.com/photo-1555022839-843343cb43a6?w=800&q=80",
    category: "nursery",
    isFeatured: true,
  },
  {
    _id: "baby_4",
    name: "BPA-Free Silicone Teether",
    description: "Textured silicone teether made from 100% food-grade material. Safely soothes sore gums.",
    price: 12.00,
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80",
    category: "toys",
    isFeatured: true,
  },
  {
    _id: "baby_5",
    name: "Ultra-Soft Bamboo Diapers",
    description: "Eco-friendly, highly absorbent bamboo diapers that offer maximum leak protection and softness.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&q=80",
    category: "essentials",
    isFeatured: false,
  },
  {
    _id: "baby_6",
    name: "Advanced Video Baby Monitor",
    description: "High-definition video monitor with night vision, two-way audio, and secure connection to keep an eye on your little one.",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?w=800&q=80",
    category: "safety",
    isFeatured: true,
    isOnSale: true,
    discountPercent: 10,
  },
  {
    _id: "baby_7",
    name: "Plush Bunny Comforter",
    description: "Incredibly soft bunny plush toy and blanket hybrid, designed to be baby's first cuddly friend.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1555985202-12975b0235dc?w=800&q=80",
    category: "toys",
    isFeatured: true,
  },
  {
    _id: "baby_8",
    name: "Gentle Baby Wash & Shampoo",
    description: "Tear-free, hypoallergenic baby bath wash made with natural oatmeal to nourish and protect delicate skin.",
    price: 14.50,
    image: "https://images.unsplash.com/photo-1617468176846-5915749f7e44?w=800&q=80",
    category: "bath",
    isFeatured: true,
  }
];
